In [1]:
import pandas as pd
import re
import pickle
from urllib.request import Request, urlopen
import bs4 as bs
import lxml

In [2]:
with open('../Data/news.pkl', 'rb') as f:
    news = pickle.load(f)

In [3]:
with open('../Data/all_muckrack_links.pkl', 'rb') as f:
    data = pickle.load(f)

In [4]:
data

,author,article_count,request_url,redirect_url,method,confidence
0,Neil Shaw,523,https://muckrack.com/neil-shaw,https://muckrack.com/neil-shaw-1,brute force,-
1,James Rodger,512,https://muckrack.com/james-rodger,https://muckrack.com/james-rodger,brute force,-
2,Jack Davis,251,https://muckrack.com/jack-davis,https://muckrack.com/jack-davis,brute force,-
3,Adam Wells,223,https://muckrack.com/adam-wells,https://muckrack.com/adam-wells,brute force,-
4,Sophie McCoid,218,https://muckrack.com/sophie-mccoid,https://muckrack.com/sophie-mccoid,brute force,-
...,...,...,...,...,...,...
3833,Levi Sumagaysay,10,https://muckrack.com/levi-sumagaysay,https://muckrack.com/levi-sumagaysay,brute force,-
3834,Ben Ashford,10,https://muckrack.com/ben-ashford,https://muckrack.com/ben-ashford,brute force,-
3835,Craig Brown,10,https://muckrack.com/craig-brown,https://muckrack.com/craig-brown,brute force,-
3836,Courtney Connley,10,https://muckrack.com/courtney-connley,https://muckrack.com/courtney-connley,brute force,-
3837,MATTHEW PERRONE,10,https://muckrack.com/matthew-pera,https://muckrack.com/matthew-pera,no match,0.83

In [5]:
beats = []

In [6]:
def find_beats(url):
    req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    sauce = urlopen(req).read()
    soup = bs.BeautifulSoup(sauce,'lxml')
    try:
        beat = []
        temp = soup.find(class_ = 'person-details-beats').find_all('a')
        for i in temp:
            beat.append(i.getText())
        beat = ', '.join(beat)
    except:
        beat = '-'
    return beat

In [7]:
for i in range(len(data)):
    try:
        beats.append(find_beats(data.iloc[i].redirect_url))
    except:
        beats.append('-')
    if i % 100 == 0:
        print(i)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800

In [10]:
beats[-5:]

['Business and Finance, Technology, U.S.',
 'U.S.',
 '-',
 'Business and Finance, U.S.',
 'U.S. Regional']

In [9]:
data.redirect_url

0            https://muckrack.com/neil-shaw-1
1           https://muckrack.com/james-rodger
2             https://muckrack.com/jack-davis
3             https://muckrack.com/adam-wells
4          https://muckrack.com/sophie-mccoid
                        ...
3833     https://muckrack.com/levi-sumagaysay
3834         https://muckrack.com/ben-ashford
3835         https://muckrack.com/craig-brown
3836    https://muckrack.com/courtney-connley
3837        https://muckrack.com/matthew-pera
Name: redirect_url, Length: 3838, dtype: object

In [11]:
data.Beat = beats

<ipython-input-11-bc250de9b7d1>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.Beat = beats

In [14]:
len(beats)

3838

In [15]:
data['Beat'] = beats

In [16]:
data

,author,article_count,request_url,redirect_url,method,confidence,Beat
0,Neil Shaw,523,https://muckrack.com/neil-shaw,https://muckrack.com/neil-shaw-1,brute force,-,United Kingdom
1,James Rodger,512,https://muckrack.com/james-rodger,https://muckrack.com/james-rodger,brute force,-,United Kingdom
2,Jack Davis,251,https://muckrack.com/jack-davis,https://muckrack.com/jack-davis,brute force,-,"Politics, Religion"
3,Adam Wells,223,https://muckrack.com/adam-wells,https://muckrack.com/adam-wells,brute force,-,"Sports, U.S."
4,Sophie McCoid,218,https://muckrack.com/sophie-mccoid,https://muckrack.com/sophie-mccoid,brute force,-,"Arts and Entertainment, United Kingdom"
...,...,...,...,...,...,...,...
3833,Levi Sumagaysay,10,https://muckrack.com/levi-sumagaysay,https://muckrack.com/levi-sumagaysay,brute force,-,"Business and Finance, Technology, U.S."
3834,Ben Ashford,10,https://muckrack.com/ben-ashford,https://muckrack.com/ben-ashford,brute force,-,U.S.
3835,Craig Brown,10,https://muckrack.com/craig-brown,https://muckrack.com/craig-brown,brute force,-,-
3836,Courtney Connley,10,https://muckrack.com/courtney-connley,https://muckrack.com/courtney-connley,brute force,-,"Business and Finance, U.S."
3837,MATTHEW PERRONE,10,https://muckrack.com/matthew-pera,https://muckrack.com/matthew-pera,no match,0.83,U.S. Regional

In [17]:
data.to_pickle('../Data/all_muckrack_links.pkl')

In [18]:
with open('../Data/all_muckrack_links.pkl', 'rb') as f:
    data = pickle.load(f)
data.head()

,author,article_count,request_url,redirect_url,method,confidence,Beat
0,Neil Shaw,523,https://muckrack.com/neil-shaw,https://muckrack.com/neil-shaw-1,brute force,-,United Kingdom
1,James Rodger,512,https://muckrack.com/james-rodger,https://muckrack.com/james-rodger,brute force,-,United Kingdom
2,Jack Davis,251,https://muckrack.com/jack-davis,https://muckrack.com/jack-davis,brute force,-,"Politics, Religion"
3,Adam Wells,223,https://muckrack.com/adam-wells,https://muckrack.com/adam-wells,brute force,-,"Sports, U.S."
4,Sophie McCoid,218,https://muckrack.com/sophie-mccoid,https://muckrack.com/sophie-mccoid,brute force,-,"Arts and Entertainment, United Kingdom"